Rework script to not use kubectl run
- https://github.com/kubernetes/kubernetes/issues/27264
- kubectl run is quite limited in functionality if the spod spec is
complex

diff --git a/orchest b/orchest
--- a/orchest
+++ b/orchest
@@ -1,33 +1,84 @@
 #!/bin/bash
+# Generally speaking, the script will:
+# - make sure the script and repo version equals the deployed cluster
+# - launch a orchest-ctl pod in-cluster
+# - wait for it to be ready
+# - attach to it and run the CLI command
+# - cleanup on exit
+
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 # Make sure the orchest namespace exists. Necessary only if Orchest is
 # being installed.
 minikube kubectl -- create namespace orchest  > /dev/null 2>&1
 
+# Script and dependencies, i.e. yaml files.
+repo_version=$(git describe --tags --abbrev=0)
+# The deployment.
+cluster_version=$(kubectl get namespace orchest -o jsonpath='{.metadata.labels.version}')
+# K8S_TODO: fix this once we actually stop using latest.
+cluster_version=test
+
+# Will be empty only if Orchest has not been installed yet.
+if [ -n "$cluster_version" ]; then
+    if [ "$repo_version" != "$cluster_version" ]; then
+        msg="The Orchest cluster version (${cluster_version}) is different from this
+        repository version (${repo_version}). Make sure those are in sync. To do that,
+        checkout the repo at a commit which tag matches the cluster version. For
+        example, first run (needed if the cluster is at a more recent version than
+        the repository):\n
+        "
+        echo -e $msg
+        echo -e "\tgit pull origin\n"
+        echo -e "Then checkout the required release version:\n"
+        echo -e "\tgit checkout tags/${cluster_version}"
+        # K8S_TODO: enable this once we actually stop using latest.
+        # exit 1
+    fi
+fi
+
 # Make sure orchest-ctl has the right permissions.
 minikube kubectl -- apply -f "$DIR/deploy/orchest-ctl/rbac" > /dev/null
 
-# Notes:
-# 
-# currently -it is always used because it's a requirement for --rm.
-# 
-# The service account is set this way because --serviceaccount is a
-# quite recent addition to kubectl. Also
-# https://github.com/kubernetes/kubernetes/issues/63214
-# 
-# --quiet and 2>/dev/null will silence messages from kubectl, not the
-# container.
-minikube kubectl -- run orchest-ctl \
-    --quiet \
+image="orchest/orchest-ctl:${repo_version}"
+# K8S_TODO: fix this once we actually stop using latest.
+image="orchest/orchest-ctl"
+
+set -e
+
+# TODO: passing an argument containing @ will break this.
+pod=$(sed -e "s@%IMAGE%@$image@g" -e "s@%VERSION%@$repo_version@g" \
+-e "s@%COMMAND%@$@@g" "$DIR/deploy/orchest-ctl/pod.yml" | \
+minikube kubectl -- create -n orchest -o name -f -)
+
+# Make sure to cleanup the pod on exit.
+function on_exit {
+    # Avoid funny race conditions.
+    for i in {1..100}; do minikube kubectl -- get -n orchest "${pod}" \
+        > /dev/null 2>&1 && break; done
+    minikube kubectl -- delete -n orchest "${pod}" > /dev/null 2>&1
+}
+trap on_exit EXIT
+
+# Necessary because
+# https://github.com/kubernetes/kubernetes/issues/83242 Not: not
+# sleeping here because not all sleep implementations support floating
+# point values, and sleeping for 1s introuces a bad delay UX wise. It
+# doesn't go through more than 1 iteration usually.
+for i in {1..100}; do minikube kubectl -- get -n orchest "${pod}" \
+    > /dev/null 2>&1 && break; done
+
+# Wait for 15mins because the image might need to be pulled. TODO:
+# alert the user if a pull happens, then wait.
+minikube kubectl -- wait --timeout=15m --for=condition=ready -n orchest "${pod}" \
+    > /dev/null 2>&1
+
+
+# Finally, connect to the pod and run the CLI command. If you are asking
+# yoursef why we haven't used kunectl run:
+# - https://github.com/kubernetes/kubernetes/issues/27264
+# - kubectl run is quite limited in functionality if the pod spec is
+# complex
+minikube kubectl -- exec \
     -it \
-    --rm \
-    --wait \
-    --restart=Never \
-    --image=orchest/orchest-ctl \
-    --image-pull-policy=IfNotPresent \
-    --namespace=orchest \
-    -l "app=orchest-ctl" \
-    --overrides='{ "spec": { "serviceAccount": "orchest-ctl" }  }' \
-    --env "PYTHONUNBUFFERED=TRUE" \
-    -- "$@" 2> /dev/null
+    -n orchest "${pod}" orchest -- orchest "$@"
